#!/bin/bash

source .env.local

echo "$MLFOW_TRACKING_SERVER_URL"

docker run --env-file .env.local \
    -p "$HOST_PORT":"$APP_PORT" \
    -e APP_PORT="$APP_PORT" \
    -e MLFOW_TRACKING_SERVER_URL="$MLFOW_TRACKING_SERVER_URL" \
    -e EXPERIMENT_RUN_NAME="$EXPERIMENT_RUN_NAME" \
    -e MLFLOW_BEST_RESNET50V2_RUNID="$MLFLOW_BEST_RESNET50V2_RUNID" \
    -e MLFLOW_BEST_CONVNEXTTINY_RUNID="$MLFLOW_BEST_CONVNEXTTINY_RUNID" \
    -e AZURE_STORAGE_ACCESS_KEY="$AZURE_STORAGE_ACCESS_KEY" \
    -e AZURE_STORAGE_CONNECTION_STRING="${AZURE_STORAGE_CONNECTION_STRING}" \
    -e API_AUTH="$API_AUTH" \
    -e PYTHONUNBUFFERED=1 \
    local/${IMAGE_NAME}:test